#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := PSX.cpp led_control.cpp circle.cpp display.cpp rectangle.cpp levels.cpp


# header files in this project
HEADERS := PSX.hpp led_control.hpp circle.hpp display.hpp rectangle.hpp levels.hpp


# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
